# 合并操作

In [3]:
import numpy as np

In [5]:
x = np.array([1,2,3])
y = np.array([45,56,67])

In [6]:
x

array([1, 2, 3])

In [7]:
y

array([45, 56, 67])

In [8]:
np.concatenate([x,y])

array([ 1,  2,  3, 45, 56, 67])

In [13]:
z = np.array([444,444,444])
z

array([444, 444, 444])

In [14]:
np.concatenate([x,y,z])

array([  1,   2,   3,  45,  56,  67, 444, 444, 444])

In [17]:
A = np.array([[4,5,6],
             [1,2,3]])
A

array([[4, 5, 6],
       [1, 2, 3]])

In [18]:
np.concatenate([A,A],axis=1)

array([[4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3]])

In [19]:
np.concatenate([A,A],axis=0) #concatenate只能拼接相同维度的
#axis=0,表示按列拼接

array([[4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [20]:
np.concatenate([A,z.reshape(1,-1)])

array([[  4,   5,   6],
       [  1,   2,   3],
       [444, 444, 444]])

In [23]:
AA = np.concatenate([A,z.reshape(1,-1)])
AA

array([[  4,   5,   6],
       [  1,   2,   3],
       [444, 444, 444]])

In [24]:
np.vstack([A,z])

array([[  4,   5,   6],
       [  1,   2,   3],
       [444, 444, 444]])

In [26]:
B = np.full((2,2),100)
B

array([[100, 100],
       [100, 100]])

In [28]:
np.hstack([B,A])

array([[100, 100,   4,   5,   6],
       [100, 100,   1,   2,   3]])

In [35]:
L = np.arange(1000) 
L

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [37]:
%%time
a = [2*i for i in L]

Wall time: 1 ms


In [38]:
%%time
a = np.array(a)

Wall time: 1.08 ms


# 聚合操作

In [39]:
L = np.random.random(100)

In [40]:
L

array([0.08630267, 0.04102363, 0.15732058, 0.06125376, 0.78898249,
       0.66417958, 0.11798663, 0.89523251, 0.51535272, 0.41396422,
       0.28526718, 0.29526188, 0.19149317, 0.07937259, 0.10947364,
       0.56470634, 0.77344461, 0.47173642, 0.33422872, 0.91552528,
       0.14238476, 0.70098667, 0.30811646, 0.32766595, 0.73122317,
       0.74071389, 0.92316269, 0.34705265, 0.12714373, 0.61752204,
       0.7115863 , 0.09557352, 0.42389606, 0.12526   , 0.89977395,
       0.97872709, 0.77743451, 0.84836944, 0.65201877, 0.1820281 ,
       0.89618304, 0.83997134, 0.52133202, 0.28650909, 0.59851814,
       0.5271555 , 0.33399705, 0.42025901, 0.30744008, 0.34233494,
       0.16725954, 0.26936699, 0.94485603, 0.46516756, 0.69278966,
       0.21754859, 0.99375015, 0.18608588, 0.60522306, 0.09705927,
       0.08309787, 0.52644852, 0.85717494, 0.03526049, 0.59739006,
       0.88648302, 0.66750926, 0.01776095, 0.77780117, 0.95801158,
       0.3801718 , 0.75787802, 0.59093447, 0.57865366, 0.39191

In [41]:
sum(L)

45.95397132218956

In [43]:
np.sum(L)

45.95397132218958

In [44]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

140 ms ± 2.21 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.47 ms ± 11.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [45]:
np.min(big_array)

8.981676791197657e-08

In [47]:
np.max(big_array)

0.9999996923687782

In [51]:
xx = np.arange(16).reshape(4,4) 
xx

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [57]:
xx[xx[:,3]%3 == 0,:]
#打印出，第三列能被3整除所在行的元素

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])