In [4]:
import  numpy  as np

In [15]:
numpy.__version__

'1.17.4'

In [16]:
import numpy as np

In [17]:
np.__version__

'1.17.4'

In [18]:
np.zeros(10) # 默认float

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
np.zeros((3,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [24]:
np.zeros(shape=(3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [26]:
np.ones(1)

array([1.])

In [27]:
np.ones(1,dtype=int)

array([1])

In [28]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [8]:
# 创建指定元素的矩阵
xx = np.full(shape=(3,5),fill_value=22) # 参数名可以省略
xx

array([[22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22]])

In [10]:
xx.shape[1]

5

### arange

In [32]:
[i for i in range(0,12,2)] # 0-12，步长为2，默认为1(步长不能为浮点数)

[0, 2, 4, 6, 8, 10]

In [33]:
np.arange(1,22,2)
# 步长可以为float，默认为1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [34]:
np.arange(1,2,0.2)

array([1. , 1.2, 1.4, 1.6, 1.8])

### linspace

In [35]:
np.linspace(0,20,5)
# 把0-20，等份分为5部分，包括0，20

array([ 0.,  5., 10., 15., 20.])

In [36]:
np.linspace(0,20,11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

### random(np.random)

In [37]:
np.random.randint(0,10)

2

In [38]:
np.random.randint(0,10,10)

array([3, 8, 9, 0, 5, 1, 7, 0, 2, 5])

In [39]:
np.random.randint(2,6,size=(3,3))

array([[4, 4, 2],
       [2, 4, 5],
       [2, 2, 4]])

In [42]:
np.random.seed(666)

In [43]:
np.random.randint(2,6,size=(3,3))

array([[2, 4, 3],
       [4, 4, 4],
       [3, 4, 2]])

In [44]:
np.random.seed(666) 
# 使用相同的seed( )值，则每次生成的随即数都相同
np.random.randint(2,6,size=(3,3))

array([[2, 4, 3],
       [4, 4, 4],
       [3, 4, 2]])

In [45]:
np.random.random()
# 生成一个随机float

0.33596835294889804

In [46]:
np.random.random((2,3))
# 均匀生成

array([[0.24434285, 0.25987554, 0.28116849],
       [0.46284169, 0.23340091, 0.76706421]])

In [48]:
np.random.normal()
# 对应于np.random.normal(loc=0, scale=1, size),
# （均值，方差，大小）
# 标准正态分布

1.2008913081264763

In [54]:
np.random.normal(0,1,1)

array([0.91860824])

In [55]:
np.random.normal(0,1,(3,3))

array([[ 0.40180184,  0.53770265, -0.03535741],
       [ 0.07666546, -0.41779575,  0.96714372],
       [-0.21326813,  0.44076692,  0.69339587]])

In [56]:
np.random.normal?
# ? 可以看到关于它的使用说明
#help(np.random.normal)

In [59]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
y = np.arange(9).reshape(3,3)
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 基本属性

In [62]:
x.ndim

1

In [63]:
y.ndim

2

In [64]:
x.shape

(10,)

In [65]:
y.shape

(3, 3)

In [66]:
x.size

10

In [67]:
y.size

9

# numpy.array 的数据访问

In [98]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
x[3]

3

In [70]:
y[(2,2)]

8

In [71]:
y[2,1]

7

In [72]:
y[:2,:3]
#前两行，前三列

array([[0, 1, 2],
       [3, 4, 5]])

In [73]:
y[:2,::2]

array([[0, 2],
       [3, 5]])

In [74]:
y[::-1,::-1]

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

In [75]:
y[0,:]

array([0, 1, 2])

In [87]:
y[:,0]

array([0, 3, 6])

In [88]:
sub_y = y[:2, :3] 
sub_y

array([[0, 1, 2],
       [3, 4, 5]])

In [89]:
sub_y[0,0]=111
sub_y

array([[111,   1,   2],
       [  3,   4,   5]])

In [91]:
y[0,0]=0

In [92]:
sub_y

array([[0, 1, 2],
       [3, 4, 5]])

In [94]:
sub_y = y[:2,:2].copy()
sub_y

array([[0, 1],
       [3, 4]])

In [95]:
sub_y[0,0]=111
sub_y

array([[111,   1],
       [  3,   4]])

In [96]:
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# reshape

In [99]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
x.shape

(10,)

In [106]:
A=x.reshape(2,5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [110]:
B = x.reshape(1,10)
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [109]:
B.ndim

2

In [111]:
x.reshape(10,-1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [112]:
x.reshape(-1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [113]:
x.reshape(-1,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])