In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from sklearn import datasets

digits = datasets.load_digits()
X=digits.data
y=digits.target.copy()

y[digits.target==9] = 1
y[digits.target!=9] = 0

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=666)

In [7]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)
y_predict = log_reg.predict(X_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [8]:
from sklearn.metrics import f1_score
f1_score(y_test, y_predict)

0.8674698795180723

In [9]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test,y_predict)

array([[403,   2],
       [  9,  36]], dtype=int64)

In [10]:
from sklearn.metrics import precision_score

precision_score(y_test, y_predict)

0.9473684210526315

In [11]:
from sklearn.metrics import recall_score
recall_score(y_test,y_predict)

0.8

In [12]:
log_reg.decision_function(X_test)

array([-21.39735902, -32.89792508, -16.42183202, -79.82552245,
       -48.03146329, -24.1812015 , -44.61422444, -24.24115238,
        -1.14364523, -19.00583241, -65.82449096, -50.97241449,
       -30.91700758, -45.94946599, -37.36115902, -29.51805983,
       -36.92675328, -82.81498317, -37.64207654,  -9.87652655,
        -9.27017255, -85.25654474, -16.75128134, -45.342988  ,
        -5.0256585 , -48.30303495, -11.65769081, -37.35548299,
       -25.08294548, -13.59630121, -16.59292371, -28.78646003,
       -34.3700879 , -28.52291759,  -8.11817098,  -4.60782344,
       -21.93083601, -21.8795332 , -31.16169503, -23.37107884,
       -26.90637802, -62.2373947 , -37.68480436, -66.36543692,
       -20.10582081, -16.68015402, -18.16942118, -21.54808353,
       -28.96519703, -19.61307004,   2.41717556,   7.72739041,
       -34.86772817, -42.71043916, -25.63548126, -34.75408897,
        -7.5974242 , -49.51669988, -51.52661277,  19.6644154 ,
       -10.10353853, -32.00906095, -11.49936359,  -1.43

In [13]:
log_reg.decision_function(X_test)[:10]

array([-21.39735902, -32.89792508, -16.42183202, -79.82552245,
       -48.03146329, -24.1812015 , -44.61422444, -24.24115238,
        -1.14364523, -19.00583241])

In [14]:
log_reg.predict(X_test)[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
decision_scores =log_reg.decision_function(X_test)


In [19]:
np.min(decision_scores)

-85.73241505716248

In [20]:
np.max(decision_scores)

19.904484094774055

In [21]:
y_predict_2 = np.array(decision_scores >= 5, dtype = "int")

In [23]:
confusion_matrix(y_test, y_predict)

array([[403,   2],
       [  9,  36]], dtype=int64)

In [24]:
precision_score(y_test, y_predict_2)

0.96

In [25]:
recall_score(y_test,y_predict_2)

0.5333333333333333

In [29]:
y_predict_3 = np.array(decision_scores >= -5, dtype = "int")

In [30]:
confusion_matrix(y_test, y_predict_3)

array([[390,  15],
       [  5,  40]], dtype=int64)

In [31]:
precision_score(y_test, y_predict_3)

0.7272727272727273

In [32]:
recall_score(y_test,y_predict_3)

0.8888888888888888