In [1]:
import matplotlib as mpb
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
x = iris.data
y = iris.target

In [4]:
x.shape

(150, 4)

In [5]:
y.shape

(150,)

# train-test-split

In [6]:
shuffle_indexes = np.random.permutation(len(x))


In [7]:
shuffle_indexes

array([ 16, 131,  32,  51,  36,  65,  93,  83,  87,  64, 119, 122, 148,
         4, 106,  12,  53,  92,  17,  25,  14, 138, 140,  75,  58,  89,
        24,  21,  27, 118,   2,  59,  55,  31, 132,  81,   0,  82,  86,
        85,  20, 133,  61,  15,  26,  22,  66,  13, 142,  10,  44,  84,
         7,   8, 141,   5,  50, 121,  28, 115,  95,  97,  19,   3, 123,
        38,  52,  39,  23,  29, 130,  99, 113,  43,  74, 105, 134,  73,
        69, 147, 125,  62,  79, 135, 124, 116,  77,  76,  34,  41,  35,
         9,  47, 128,  54,  80,  98, 136, 102, 114, 112,  30, 103, 146,
       139,  67,  48,  96,  11, 129,  37, 109,  45,  91, 104,  88,  49,
        57, 144,   6,  46,  18,  71,   1,  78, 117, 110,  63, 120,  68,
        42, 108, 101,  40, 107, 111, 143, 145,  90, 126,  56, 137,  72,
        70, 149, 127,  60, 100,  94,  33])

In [8]:
test_ratio = 0.2
test_size = int(len(x)*test_ratio)

In [9]:
test_size

30

In [10]:
test_indexes = shuffle_indexes[: test_size]
train_indexes = shuffle_indexes[test_size :]

In [11]:
x_train = x[train_indexes]
y_train = y[train_indexes]

x_test = x[test_indexes]
y_test = y[test_indexes]

In [12]:
from playML.model_selection import train_test_split

In [13]:
x_train,x_test,y_train,y_test  = train_test_split(x,y)

In [14]:
print(x_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [15]:
print(x_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [16]:
from playML.KNN2 import KNNclassifiers

In [17]:
my_knn_clf = KNNclassifiers(k=3)

In [18]:
my_knn_clf.fit(x_train,y_train)

KNN(k=3)

In [19]:
y_predict = my_knn_clf.predict(x_test)
y_predict

array([0, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 2, 1, 1, 2, 1, 2, 2])

In [20]:
y_test

array([0, 2, 2, 2, 1, 2, 1, 1, 1, 2, 2, 2, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 2, 2, 1, 2, 1, 2, 2])

In [25]:
sum(y_predict==y_test)

27

In [27]:
predict_rates=sum(y_predict==y_test)/len(y_test)
predict_rates

0.9

# sklearn 中的 train_test_split

In [28]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test  = train_test_split(x,y,test_size=0.2)

In [29]:
print(x_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [30]:
print(x_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [32]:
my_knn_clf = KNNclassifiers(k=3)
my_knn_clf.fit(x_train,y_train) 
y_predict = my_knn_clf.predict(x_test)
y_predict
sum(y_predict==y_test)
predict_rates=sum(y_predict==y_test)/len(y_test)
predict_rates

0.9

In [ ]:
x_train,x_test,y_train,y_test  = train_test_split(x,y,test_size=0.2,random_state = 666)# random_state = 666随机种子