### 从sklearn 中 导入鸢尾花的数据

In [1]:
import numpy as np
from sklearn import datasets

In [2]:
iris = datasets.load_iris()
x = iris.data
y = iris.target

In [3]:
x[:10,:]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

### 把导入的数据集分割成，测试数据集和训练数据集

In [4]:
from playML.model_selection import train_test_split
x_train,x_test,y_train,y_test  = train_test_split(x,y,test_ratio=0.2,seed=777)

### 导入KNN分类器

In [7]:
from playML.KNN2 import KNNclassifiers

### 导入自己封装的 均值方差归一化

In [9]:
from playML.preprocessing import StandardScaler

In [10]:
standardScaler = StandardScaler()

In [21]:
standardScaler.fit(x_train) # 对训练数据集的数据，求均值方差

In [12]:
# 测试 code
standardScaler.mean_

array([5.7825    , 3.05166667, 3.65416667, 1.15583333])

In [22]:
standardScaler.transform(x_train) # 将x根据这个StandardScaler进行均值方差归一化处理

array([[-1.84887782, -0.11760747, -1.48722374, -1.42937176],
       [ 0.77010594, -0.80048957,  0.95832525,  1.00744198],
       [-1.35002377,  0.33764726, -1.19608696, -1.29399322],
       [ 0.02182486, -0.80048957,  0.84187054,  1.00744198],
       [-0.22760216, -0.34523484, -0.03153982,  0.19517073],
       [-1.22531026,  0.79290199, -1.19608696, -1.29399322],
       [-0.97588323,  1.02052935, -1.37076903, -1.15861468],
       [-0.72645621,  1.02052935, -1.25431432, -1.29399322],
       [-1.10059675, -1.48337166, -0.20622189, -0.21096489],
       [-1.47473728,  0.79290199, -1.31254167, -1.15861468],
       [-1.72416431,  0.33764726, -1.37076903, -1.29399322],
       [ 0.64539243, -0.80048957,  0.72541582,  0.87206344],
       [-0.35231567, -1.02811693,  0.43427904,  0.05979219],
       [ 1.01953296, -0.11760747,  0.43427904,  0.33054927],
       [-0.47702918,  1.93103881, -1.1378596 , -1.02323614],
       [ 1.14424648,  0.56527462,  1.19123468,  1.81971322],
       [ 0.77010594, -0.

In [14]:
x_train = standardScaler.transform(x_train)
x_train

array([[-1.84887782, -0.11760747, -1.48722374, -1.42937176],
       [ 0.77010594, -0.80048957,  0.95832525,  1.00744198],
       [-1.35002377,  0.33764726, -1.19608696, -1.29399322],
       [ 0.02182486, -0.80048957,  0.84187054,  1.00744198],
       [-0.22760216, -0.34523484, -0.03153982,  0.19517073],
       [-1.22531026,  0.79290199, -1.19608696, -1.29399322],
       [-0.97588323,  1.02052935, -1.37076903, -1.15861468],
       [-0.72645621,  1.02052935, -1.25431432, -1.29399322],
       [-1.10059675, -1.48337166, -0.20622189, -0.21096489],
       [-1.47473728,  0.79290199, -1.31254167, -1.15861468],
       [-1.72416431,  0.33764726, -1.37076903, -1.29399322],
       [ 0.64539243, -0.80048957,  0.72541582,  0.87206344],
       [-0.35231567, -1.02811693,  0.43427904,  0.05979219],
       [ 1.01953296, -0.11760747,  0.43427904,  0.33054927],
       [-0.47702918,  1.93103881, -1.1378596 , -1.02323614],
       [ 1.14424648,  0.56527462,  1.19123468,  1.81971322],
       [ 0.77010594, -0.

In [15]:
x_test_standard = standardScaler.transform(x_test) # 测试数据集，归一化
x_test_standard

array([[ 2.3913816 ,  1.70341145,  1.77350825,  1.4135776 ],
       [-1.22531026, -0.11760747, -1.31254167, -1.42937176],
       [ 1.64310053, -0.11760747,  1.30768939,  1.27819906],
       [-0.10288865, -1.2557443 ,  0.78364318,  1.14282052],
       [ 0.3959654 , -0.34523484,  0.60896111,  0.33054927],
       [-0.6017427 ,  1.47578408, -1.25431432, -1.29399322],
       [ 2.3913816 , -0.11760747,  1.42414411,  1.54895614],
       [ 0.77010594, -0.5728622 ,  1.13300732,  1.27819906],
       [-0.10288865,  1.70341145, -1.1378596 , -1.15861468],
       [-0.85116972,  1.47578408, -1.25431432, -1.02323614],
       [ 1.89252755, -0.34523484,  1.54059882,  0.87206344],
       [ 0.3959654 , -0.5728622 ,  0.60896111,  0.05979219],
       [-0.35231567, -1.2557443 ,  0.20136961,  0.19517073],
       [ 1.3936735 ,  0.11001989,  1.01655261,  1.27819906],
       [ 0.52067891,  0.79290199,  1.01655261,  1.54895614],
       [ 0.3959654 , -1.02811693,  1.13300732,  0.33054927],
       [-0.97588323,  0.

In [17]:
my_knn_clf = KNNclassifiers(k=3) # 系数 

In [23]:
my_knn_clf.fit(x_train,y_train) # 对训练数据集，进行拟合

KNN(k=3)

In [19]:
my_knn_clf.score(x_test_standard, y_test) # 分类准确度

0.9666666666666667